name=CSLedited_ESP32_IDF5_HTTPS_Server
version=1.1.1-csl1
author=Frank Hessel <frank@fhessel.de>
maintainer=Community Sensor Lab
sentence=Community Sensor Lab modified copy of ESP32_IDF5_HTTPS_Server with increased browser header limits for ESP32 HTTPS provisioning.
paragraph=Community Sensor Lab modified copy of ESP32_IDF5_HTTPS_Server, maintained upstream by Jack Jansen and based on the original ESP32 HTTPS Server by Frank Hessel. This copy increases HTTPS request/header buffer limits to support modern browsers during local sensor provisioning.
category=Communication
url=https://github.com/jackjansen/esp32_idf5_https_server
architectures=esp32
includes=HTTPSServer.hpp,HTTPRequest.hpp,HTTPResponse.hpp
